### ISSUE TITLE
Archive or Delete this repository?

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/rdl-docs#7]
Documentation was moved to https://github.com/GFDRR/rdl-standard/tree/0.2-dev/docs

It is suggested to archive or delete this repository.

I recommend deletion for the reason that documentation content has been substantially updated in new repo and there is no useful reason to keep this repo as an archive. This might also create confusion for users looking for RDLS documentation code.

@matamadio and @stufraser1 what is your view?

**Comment by matamadio** [comment]
Well we moved the docs in the same repo as rdl, so this one can go.
I just archive it.
